name: build-and-release

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [macos-latest, ubuntu-latest]
        steps:
            - name: checkout repo
              uses: actions/checkout@v2
            - name: build application
              run: ./make.sh
          
            - name: upload result
              uses: actions/upload-artifact@v2
              with:
                name: build-${{ matrix.os }}
                path: dist/*.tar.bz2

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v2
              with:
                name: build-ubuntu-latest
            - name: Display structure of downloaded files
                run: ls -R

            - name: Release result
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: *.tar.bz2
